### ISSUE TITLE
[Question] Is it possible to use a custom Docker repository?

### ISSUE THREAD

**Issue by Craga89** [JeanRev/TeamcityDockerCloudPlugin#1]
First off, great work on the plugin, it looks really promising. We're looking at using this for our internal company build process, so it would be great if custom Docker image repositories were supported! 

Currently it looks like you can only specify a default Docker image repository tag? Apologies if I've just missed a setting somewhere.

**Comment by JeanRev** [comment]
Using an image hosted in a private registry should actually work transparently, you just have to prefix the image name with the registry hostname/ip and port just like on the CLI. For example: 172.17.0.2:5000/my_own_teamcity_agent:1.0

Currently, the plugin will always try to pull the newest image matching the provided name before creating  the container. If the image cannot be pulled for some reason, the plugin will assume that it is already available in the daemon local repository and try proceed with the container creation. If the image is not available in the daemon local repo, you will then only receive a generic "Image not found" error. Failure to pull an image is currently just logged in the _logs/teamcity-clouds.log_ file of your teamcity installation (but this should probably be reported in the container-test UI as well... this will need to be addressed).

Note that the docker daemon you are connecting to must also be configured in such a way it is able to access your private registry (either with or without TLS).

Thank you for reporting.

**Comment by Craga89** [comment]
Perfect! Might I suggest adding a little help text below the input for future users? May be helpful and save you some repeated questions! 👍
