### ISSUE TITLE
No Option to assign the agent pool in Docker Cloud integration

### ISSUE THREAD

**Issue by nchidipothu** [JeanRev/TeamcityDockerCloudPlugin#2]
Hi,

I did not see the option to assign the agent pool for added docker image in docker cloud integration.

Default it's going to "Default Pool"

Can you please help me at this.

Thanks,
Naresh Ch

**Comment by JeanRev** [comment]
Hi Naresh,

You should be able to assign a cloud image to a specific agent pool from the "Pools" configuration interface.
![agent_pools](https://cloud.githubusercontent.com/assets/8666989/21963213/b65b18cc-db36-11e6-99b6-10cc147d6d4c.png)

The cloud image name is composed of the image profile name (as specified in the Docker cloud settings), and the docker image name (which will be dynamically resolved when using the official TeamCity agent images).

All agents instantiated from this image should then be automatically assigned to the corresponding pool.

**Comment by sharov** [comment]
Hi @JeanRev!

When new images run, they go to Default pool

**Comment by JeanRev** [comment]
Sorry for the delay. There is indeed a glitch preventing the cloud image association with a given agent pool to be persisted. This is now fixed, the fix will be available in the next release. Thank you for reporting.

**Comment by JeanRev** [comment]
v0.2.3 has just been released.

**Comment by pinkal-vansia** [comment]
+1 thanks @nchidipothu @JeanRev I was facing same issue. Hope to try it now.
