### ISSUE TITLE
Docker Image is not removing from teamcity cloud profile

### ISSUE THREAD

**Issue by nchidipothu** [JeanRev/TeamcityDockerCloudPlugin#20]
Hi,

We have added multiple docker images in one cloud profile. when i delete it's deleting from list and saving my changes. But, when i re-open the cloud profile the same image is showing. 

I have done  multiple times, but same issue. 

Can you please help with this.

**Comment by JeanRev** [comment]
Hi,

There is indeed a missing Javascript callback when deleting images. The JSON structure hosting the image configuration is then not updated as it should... This issue has been here for a while...

As a temporary workaround, you can delete the table entry, and then open and save any other cloud image. The deletion should then be effective.

I'll release a new minor version handling both issues you reported, middle of the next week.

Thank you for reporting!
