### ISSUE TITLE
Running Container are killing when i click SAVE in docker profile.

### ISSUE THREAD

**Issue by nchidipothu** [JeanRev/TeamcityDockerCloudPlugin#21]
Hi,

We have multiple docker profiles and container and builds are in progress, now the problem is, when i click on "SAVE" in docker profile(even with out any modifications) the running containers are killing.

We used to add/update docker container, so it's causing blocker and running build is getting terminating as build agent is terminated.

Can you please help with this.

Thanks,
Nchidipothu

**Comment by JeanRev** [comment]
Hi Naresh,

This is a known limitation.

The TeamCity cloud API currently offers a single callback to dispose a cloud client (the entity managing cloud instances, or in our case, Docker containers). This callback is invoked:
- When the cloud configuration is persisted (after a click on 'Save' in the plugin settings, independently of if the configuration was actually changed or not). A new cloud client will then be immediately created with the possibly updated configuration.
- Before the shutdown of the TC server.
- When the cloud client configuration is disabled/removed.

The exact reason why a client is disposed is not known to the plugin.

It would theoretically be possible to preserve containers across reconfiguration of the plugin, or shutdown of the TC server, but their settings won't be updated to reflect a possible change of configuration. This might be a bit disconcerting for the user, and would induce a significant layer of complexity into the current container management logic. It would be then also required to manually dispose existing containers in some situations, for example when a cloud profile is removed.

Ultimately, this is probably something that will be implemented as a configurable behavior, I would say in one of the next few releases.

I created a new issue to track progress on this feature: #23 

I propose that we move the current discussion over there.
