### ISSUE TITLE
Container Memory is not updating correctly when i give value in "GiB and MiB"

### ISSUE THREAD

**Issue by nchidipothu** [JeanRev/TeamcityDockerCloudPlugin#22]
Hi,

We are giving container memory as 4 GiB and when it run, we can see only 512MB, but in case we provide 4GiB value in terms of "bytes" then it is working perfectly.

The same issue is for MiB, not tested with KiB.

Thanks,
Nchidipothu

**Comment by JeanRev** [comment]
Hi Naresh,

Well spotted! The multiplication factor for these two units was a bit off. The fix is part of today's release.

Thank you again for reporting these issues, this is highly appreciated.
