### ISSUE TITLE
Support for storage options

### ISSUE THREAD

**Issue by marcos-vale** [JeanRev/TeamcityDockerCloudPlugin#26]
How to increase the docker agent container disk space?

You can achieve that in "docker run" command by using the parameter "--storage-opt size=50G", but how to do that in Teamcity?

**Comment by JeanRev** [comment]
Hi @marcos-vale 

The storage-options parameters are not integrated yet in the plugin properties page... But I'll try to make them part of the next major release, along with security options (#16).

**Comment by JeanRev** [comment]
Fixed with #27
