### ISSUE TITLE
Update Cloud Profile

### ISSUE THREAD

**Issue by srizzling** [JeanRev/TeamcityDockerCloudPlugin#30]
Hi,

I have been trying to find a way to programatically update cloud profiles so that I can store and update cloud profiles via a structed format.

Do you know how I can do this with the docker plugin? Seems like teamcity offers no RESTAPI, and I had a quick look by inspecting the AJAX, and it seems like I need a "private key" which I don't know where that would exist..

Thanks,
Sriram

**Comment by JeanRev** [comment]
Hi Sriram,

The Teamcity rest API offers indeed no capability to update cloud profiles yet (but there seems to be an open issue to address this at JB and you may want to vote for it: [TW-41139](https://youtrack.jetbrains.com/issue/TW-41139)).

The Java API will probably not be much helpful either, so your best bet would be indeed a script to interact directly with the cloud profile settings page.

A request to update a cloud profile with curl, for example, could looks like this:
```bash
curl  --user '[yourusername]:[yourpassword]' 'http://localhost:8111/clouds/admin/cloudAdminProfile.html?projectId=_Root'  --data 'projectId=_Root&prop%3AprofileName=testerror&prop%3AprofileDescription=&-ufd-teamcity-ui-cloudType=Docker&cloudType=VRDC&prop%3AterminateTimeOut=30&prop%3Atotal-work-time=&prop%3Anext-hour=&prop%3Arun.var.teamcity.docker.cloud.use_default_unix_socket=true&prop%3Arun.var.teamcity.docker.cloud.instance_uri=unix%3A%2F%2F%2Fvar%2Frun%2Fdocker.sock&prop%3Arun.var.teamcity.docker.cloud.tested_image=%7B&prop%3Arun.var.teamcity.docker.cloud.client_uuid=97a5c557-f985-495d-8104-ec17d4dd583b&prop%3Asource_images_json=%5B%7B%22profileId%22%3A%22VRDC-10%22%2C%22agent_pool_id%22%3A%220%22%2C%22source-id%22%3A%22test%22%7D%5D&prop%3Arun.var.teamcity.docker.cloud.img_param=%5B%7B%22Administration%22%3A%7B%22Version%22%3A4%2C%22RmOnExit%22%3Afalse%2C%22PullOnCreate%22%3Afalse%2C%22MaxInstanceCount%22%3A2%2C%22UseOfficialTCAgentImage%22%3Afalse%2C%22Profile%22%3A%22test%22%7D%2C%22Container%22%3A%7B%22Image%22%3A%22test_commited%3A1.1%22%2C%22HostConfig%22%3A%7B%22OomKillDisable%22%3Afalse%2C%22Privileged%22%3Afalse%7D%7D%2C%22Editor%22%3A%7B%22MemoryUnit%22%3A%22bytes%22%2C%22MemorySwapUnit%22%3A%22bytes%22%7D%7D%5D&prop%3Arun.var.teamcity.docker.cloud.daemon_info=&prop%3Arun.var.teamcity.docker.cloud.server_url=&prop%3AagentPushPreset=&action=edit&profileId=VRDC-1&save=Save&publicKey=[the public key string]'
```
 You will need to adapt the example with your teamcity user and password. The TeamCity URL, the projectId (here _Root for the root project) to which the profiled is tied, and the profileId parameter may need to be changed to match your setup (you can simply copy them from the URL in the address bar when you are manually editing the profile). 
 
The 'publicKey' post parameter is a bit trickier. It's used in some server interactions when editing a project configuration. The key is provided as an hidden input field when loading the form initially and must be submitted back to the server on each request. It is also regenerated after each start of the server.

To fetch it, you may simply do something like this:
curl --user '[yourusername]:[yourpassword]' 'http://localhost:8111/admin/editProject.html?projectId=_Root&tab=clouds&action=edit&profileId=VRDC-1&showEditor=true' | grep publicKey
 
The configuration of the cloud images is stored in a JSON structure in the field ```run.var.teamcity.docker.cloud.img_param``` encoded in a url-safe way.

Most of the field names are pretty self-explanatory, but do not hesitate to ask back if you are unsure.

Just out of curiosity, can I ask which use case you are trying to fulfill? (maybe we can derive some new feature from it)

**Comment by srizzling** [comment]
OMG! Thank you so much for the help! 

I have been spending a while trying to figure out what that publicKey could be but grep the key from that request seems to be a nice alternative.

Our use case for something like this would be define our cloud profiles and settings in yaml files in source control, have them automatically merged in. We have around 7 teamcites, and it is cumbersome to update.

We also have quite a few agent configurations which we are looking to containerize. We know that with the recent version of teamcity you add cloud profiles to your projects, but we have had issues in the past, and think that storing the cloud profiles in version control, and opening up access so developers can make PR's will be an awesome place for us to be.

I also know you can store this config in version control already, but it stores ALL the config the project, while we only really care about the cloud profiles, and other teams use the versioned kotlin DSL, while other teams don't so it doesn't work like we would like it too.

 I had started working on this, but this has given me a bit more to get my teeth stuck into! Thanks!

**Comment by JeanRev** [comment]
You're welcome :-)

I'll close the issue for now but you can keep posting if you require more information.

**Comment by srizzling** [comment]
@JeanRev I have started to work on this, but I am having trouble retreiving a current profile given the browser sends the whole profile as a whole form.

**Comment by srizzling** [comment]
Ignore that, I found this endpoint /app/rest/projects/_Root/projectFeatures?locator=type:CloudProfile
