### ISSUE TITLE
Insecure Registry support

### ISSUE THREAD

**Issue by srizzling** [JeanRev/TeamcityDockerCloudPlugin#32]
This perhaps could be a bad suggestion as it isn't best practice but would there be any chance to support insecure registries? 

Within the docker client this can be set in the `daemon.json`. I'm assuming there is a java client config equivalent that needs to be exposed for in UI for it to work, or am I missing something obvious?

Thanks,
Sriram

**Comment by srizzling** [comment]
Nevermind.. Not being smart, the setting is done on daemon.json

**Comment by JeanRev** [comment]
No problem, this can be confusing at first :-)

So yes, communication between the daemon and the registry must be configured at the daemon level.

The plugin will actually only communicate with the Docker hub registry to list image tags needed to resolve the official agent docker image (something that the daemon API does not permit to do directly).
