### ISSUE TITLE
No agents running - what triggers them?

### ISSUE THREAD

**Issue by iainfogg** [JeanRev/TeamcityDockerCloudPlugin#37]
Hi, following my upgrade to 2017.2.2 from 10.0.0.4 plus upgrading to the latest version of your plugin, I'm not getting any agent running. I can create a test agent successfully, but nothing's firing up the proper agent to run my builds.

I read through the wiki and could see plenty of info about getting rid of containers, but I couldn't find what triggers the build, or how to find out what the problem is.

If I run docker ps on the host, it doesn't show anything running, so it's not as if it's running an upgrade. And there's nothing waiting for authorisation either.

If I manually fire up an agent from the command line, that works fine. It's getting the plugin to initiate it that seems to be the problem.

Anything I can try?

**Comment by JeanRev** [comment]
Hi again :-)

There are several possible reasons why a cloud agent won't be started to process a build job.

You should first check that no error is displayed in the "Agents" -> "Cloud" tab, or along the cloud profile entry in the project settings page (if you migrated from TC 10.x, all cloud profiles you had defined have been automatically moved from the TeamCity main settings page, to the "root project"  settings). 

If no error is reported in the UI, you must also ensure that the project you are trying to build is compatible with your cloud image, according to any agent requirements and/or agent pool association that you may have defined. TeamCity usually issues a warning message, if it didn't find any compatible agent for a given build job.

Finally, you should also check the teamcity server logs for anything suspicious (teamcity-server.log and teamcity-clouds.log are the most interesting files to look into).
