### ISSUE TITLE
Incorrect calculation of idle time

### ISSUE THREAD

**Issue by sharov** [JeanRev/TeamcityDockerCloudPlugin#4]
I set "Terminate instance idle time" == 1, tasks don't execute.
It seems that idle time calculated since agent start, instead of a time when it ready for working.

In tab "Agent / Cloud" I see 
![2017-01-23 11 25 03](https://cloud.githubusercontent.com/assets/30379/22194944/c8d65d44-e15e-11e6-9497-c5a0b574800e.png)

**Comment by JeanRev** [comment]
I was able to reproduce the issue. The cloud instance start timestamp is currently not updated as expected which may in turn causes cloud instances to be disposed sooner as they should when low timeouts are used.

This should be fixed shortly. If you have the time to give it a try when the new version is released (in the next few days) that would be great. Thank you for reporting!

**Comment by JeanRev** [comment]
Solved with 6175f49d2d637836ddbcbf1dbc17bd05d8383374.
