### ISSUE TITLE
Cloud image is not configured to stop agents gracefully.The agent that was not stopped gracefully might be assigned with the build. 

### ISSUE THREAD

**Issue by Vampire** [JeanRev/TeamcityDockerCloudPlugin#42]
I'm not sure whether the actual warning comes from your plugin or from TeamCity itself, but somehow I made one of my agents enter this state and I don't find a way to get it out again.

And actually i also don't quite understand what it means, especially the part about "might be assigned with the build". What build and how assigned?

Can you shed some light, or fix something or tell me how I can fix this or what it actually means and what effect it has?

**Comment by JeanRev** [comment]
I have never seen such message. It probably relates to the fact that an agent hosted in a container was killed, most likely because the container didn't stop in a timely fahsion. If you didn't do it already, I would try to increase the stop-timeout in your container settings. If you didn't specify one, then the default Docker timeout of 10s is observed.
Note that no timeout is observed when the cloud client is being disposed. This allows to exit as quickly as possible when when the server is shutting down (or when the cloud profile is reconfigured, since we can't differentiate these two events).

In addition, the cloud image you are using must also be correctly configured to react correctly to SIGTERM (or to whatever signal you configured in your container settings). The default bootstrap script of the official teamcity agent is supporting this.

**Comment by Vampire** [comment]
I doubt it is a general or settings problem.
I might have caused it manually by deleting the wrong container (a running agent container), I'm not sure.
But I tried various things to leave the state again.
I have three Agent profiles with 1 max instance each, because I also want to use the docker wrapper without docker-in-docker and thus need distinct build-agent directories.
Because of that also each agent profile has its own image with Dockerfile

```docker
FROM jetbrains/teamcity-agent:2018.1.1

ARG i

# Add user with same uid and gid as build image for easier file sharing
RUN groupadd -g 1001 teamcity && \
    useradd --no-log-init --shell /bin/false --create-home -g teamcity -u 1001 teamcity && \
    adduser teamcity docker && \
    rm -f /services/run-docker.sh && \
    sed -i "s!/opt/buildagent!/opt/buildagent${i}!" /run-agent.sh && \
    sed -i "s!/data/teamcity_agent!/opt/buildagent${i}!" /run-agent.sh

USER teamcity
```

so it should react properly to SIGTERM.

All three agent profiles are configured exactly the same besides 1 vs. 2 vs. 3 where appropriate.
Only one of them shows this warning and won't go away again.

**Comment by Vampire** [comment]
I also now tried to set the timeout to 60 seconds, but the image is disappearing within a few seconds after clicking "Stop" or after the idle timeout is over.

**Comment by wtigotw** [comment]
@Vampire I'm seeing a similar issue. Are the build images you are using Windows or Linux? I'm using Windows and was wondering if the ps1 script from the official TeamCity images don't support the SIGTERM properly?

**Comment by Vampire** [comment]
Linux here and SIGTERM should be handled properly. As I said, I might have caused this myself by killing the wrong container, the question is just how this warning is identified and how to make it go away again as the others that are identically setup work fine.

**Comment by wtigotw** [comment]
Well, I'm still getting up to speed on exactly what's going on, but my understanding is that the SIGTERM handling is supposed to allow the container to instruct agent process to shut down - giving it a chance to finish any ongoing builds and communicate to the server that it is being shut down. I believe the warning occurs when the container is detected as terminated by the plugin, but the agent never reported to the server that it was shutting down.

This is why @JeanRev suggested making sure the stop timeout is set appropriately. If the container was requested to shut down while in the middle of a build, by default Docker only waits ten seconds before deciding the container is unresponsive and forcibly aborting it. If the agent didn't gracefully shut down before the container was aborted, that would trigger the warning as well as cause any ongoing builds to fail.

Another possible cause would be a network hiccup that temporarily prevented the agent from communicating with the server prior to the container shutdown/kill. That could result in such a message as well.

Having said all this, I haven't sifted through all of the code in the server, agent, and plugin to confirm everything I've just said, so I'm prepared to be told all of my assumptions are wrong, too :)

With regards to my Windows image issue, I've raised something with the JetBrains team so we'll see what they say: jetbrains/teamcity-docker-agent#37

**Comment by JeanRev** [comment]
Windows containers are indeed a different story. Last time I looked into them, graceful shutdowns were simply not possible. Some progress have been made over the last year (see https://github.com/moby/moby/issues/25982), but implementing such image is still not as straightforward as it should be. I doubt that this is currently possible when using the official agent windows images.

Concerning that warning, I dug into the TC binaries, it seems that it is pretty much handled the same way that other cloud image warnings (like the one you see when starting cloud images based on outdated agents). It should basically be updated when the following conditions are met:
- The agent is reported as gone.
- The agent was reported as terminating.
- If the agent is still registered in the TC build agent manager, the warning will then be set, or cleared if it can't be found. 

Those warnings are stored in an ConcurrentHashMap, and don't seem to be persisted in DB. Judging from the code, I would assume that the warning should disappear the next time an agent is started from the same cloud image image, and gracefully stopped.

The warning should be pretty much inoffensive, but still, it might be worth reporting this at JetBrains with the information you have. IMHO, they should at least reword it. A killed agent doesn't mean that a cloud image was "configured" to always react that way. I can't do much more from my side :-/

@wtigotw thanks for the ticket

**Comment by Vampire** [comment]
Hm, now all three show that warning. *grml*
I played a bit.

I now started agent 1, which has the timeout set to 60 seconds currently.
I waited until all was settled.
Then I pressed `Stop` on the `/agents.html?tab=clouds` page.
After 7 seconds the agent container was gone from the docker agent (it is set to `Delete container when cloud agent is stopped`), but the agent was still registered in TC and the warning was shown. Also there was no `Unregistering from the server.` message in the agent logs.

I then wanted to try again and did the exact same sequence again, but this time in the logs there was the `Unregistering from the server.` line, the agent was properly instantly removed from TC and the warning is gone.

Did it again and had the first behavior again.

Did it again and had the first behavior again.

So it indeed seems to be related to graceful shutdown.
But what can make the agent container go away before the unregistering is done after 7 seconds if the timeout is 60 seconds?
The shutdown sequence was initiated on the agent, I can see that from the agent logs, I see `Received stop command from launcher` and `Starting agent shutdown sequence, reason: Stop command called`.

**Comment by Vampire** [comment]
Ok, it was indeed the official images that do **not** properly do a graceful shutdown.
It is a total gambling thing whether it works or not.
The script that runs just waits for the agent launcher to tell the agent to shutdown and then exists and thus the container is stopped.
If the agent is fast enough he can unregister on the server, otherwise you get the triangle.
Here is an according PR to the minimal image which is also the base for the non-minimal image that properly fixes this and makes it shutdown gracefully correctly now: https://github.com/JetBrains/teamcity-docker-minimal-agent/pull/27
