### ISSUE TITLE
Docker instance field always reset

### ISSUE THREAD

**Issue by GauthierPLM** [JeanRev/TeamcityDockerCloudPlugin#5]
Hi,

When creating a configuration and then opening it again, the field "Docker instance" is always reset to the default value (empty).
The value should be kept between edit and only set to an empty string on configuration creation.

I use the last version available in plugin repository (0.3.0 (build f3d1fa5616ab2ea821d411d89006b34426f0ff13)) with the official teamcity server docker image.

**Comment by JeanRev** [comment]
Hi!
Well spotted. This should be easily fixed. I'll update the current release to include the change.
Thank you for reporting.

**Comment by JeanRev** [comment]
Okay, v0.3.3 was just released with the fix and also with some other adjustments related to the handling of the instance field.

Feel free to test it and report any other issue you may encounter.
