### ISSUE TITLE
Gracelul shutdown of idle TeamCity agents

### ISSUE THREAD

**Issue by JeanRev** [JeanRev/TeamcityDockerCloudPlugin#9]
Currently, all agent containers that must be stopped as part of the normal agent lifecycle or when the server is being shut down, are stopped without timeout. This means that the corresponding container process is immediately killed and not properly interrupted.

This choice was originally motivated from the facts that:
- The official agent image currently does not react to other signals than SIGKILL.
- When the TeamCity server is being shut down, only a short time frame is available to stop all containers before the JVM gets killed. A timeout set too high could then prevent all container stop requests to be submitted on time (depending on the number of worker thread available).

A graceful shutdown of the agent processes would however improve usability, with registered agent going immediately from the "connected" to the "disconnected" state when their container is stopped .

An issue was recently submitted to fix the handling of signal in the official TeamCity agent images: JetBrains/teamcity-docker-minimal-agent#6 It would therefore makes sense to use a non-zero kill timeout at least for agents being disposed once their idle timeout is reached.

Graceful interruption of agents as part of the JVM shutdown process will however probably require a more elaborated solution that will be handled in another issue.

**Comment by VladRassokhin** [comment]
FYI, `10.0.5` and `latest` images now have fix for https://github.com/JetBrains/teamcity-docker-minimal-agent/issues/6 // Not sure if that information is relevant to this issue

**Comment by JeanRev** [comment]
Thank you @VladRassokhin this fix will be helpful.

**Comment by JeanRev** [comment]
Container stop timeout is now configurable in the plugin configuration interface and will be applied when stopping individual container instances (either when going idle, or through the cloud administration interface).
